version: '3'

services:
  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: "secret"
      MARIADB_DATABASE: "trello"
      MARIADB_USER: "root"
      MARIADB_PASSWORD: "secret"
    ports:
      - "3888:3888"
    volumes:
      - ./mariadb/:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d